### ISSUE TITLE
Renaming project name

### ISSUE THREAD

**Issue by Swoorup** [abs-lang/abs#108]
abs is bit unusual name for programming language. It is hard to search this name via a search engine.

**Comment by odino** [comment]
Hi @Swoorup, thanks for the suggestion!

At the moment I'm not considering renaming the project as it's fairly small in scope and we've seen others take funky names (Ruby, python, Go) doing just fine. I might change idea at some point but for now I'd rather focus on the current backlog without doing a name change, which would involve renaming a few things on the repo, domain name, etc.

Cheers!

**Comment by Swoorup** [comment]
Sure I have no issues with it. Just a heads up that abs refers to the following term that are commonly found in programming terminology.  

- Advanced Bash scripting guide 
- absolute function
