### ISSUE TITLE
Are command line arguments supported?

### ISSUE THREAD

**Issue by gamecubate** [abs-lang/abs#109]
Are command line arguments supported? For example, ```$ abs myscript.abs 1 2 3```.

**Comment by odino** [comment]
Hey @JBScoutBerlin, thanks for your help!

@gamecubate they are supported:

```
~ ᐅ abs
Hello alex, welcome to the ABS programming language!
Type 'quit' when you're done, 'help' if you get lost!
⧐  arg(0)
abs
```

As @JBScoutBerlin pointed out, you could try the example:

```
~ ᐅ abs ~/projects/abs/examples/args.abs some arg
abs
/home/alex/projects/abs/examples/args.abs
some
arg
```

There might be a difference in how positional arguments are treated in bash, as I simply opted for Go's [os.Args](https://github.com/abs-lang/abs/blob/master/evaluator/functions.go#L202-L220) -- if there's anything that's not clear feel free to open another issue!

Cheers!
