### ISSUE TITLE
Bug: First statement following if block's closing } fails in parse or eval 

### ISSUE THREAD

**Issue by ntwrick** [abs-lang/abs#135]
Seems to be a new problem with the parser after the else..if enhancement #133. You may have to follow the if block's closing `}` with a comment (or a `;`) otherwise the next statement fails in the parser or evaluator. You can remove the comment on line 10 to see this happen.
```
path = 'host:/local/path'
if path.contains(":") {
    # split target:path
    target, this_path = path.split(":")
} else {
    # implicit local target
    target = "localhost"
    this_path = path
}
# a comment on this line prevents parser error on the next line
result = [target, this_path]
# parser errors:
#	no prefix parse function for '=' found
#	[11:8]	result = [target, this_path]
echo(result)

```

**Comment by odino** [comment]
Taking a look, this is nasty :(

**Comment by odino** [comment]
Thanks for the report rick!

**Comment by ntwrick** [comment]
Verified working. This fixes my script. 

BTW, without error line numbers this would have been impossible to locate. It was deep in a very long script that used to work. Also, it was not obvious that there was anything wrong with the code that was triggering the parser error because it was correct. Instant return on investment :-).

**Comment by odino** [comment]
Yeah. Your PR was a manna from heaven! Thanks for taking the time to spend
fun on abs' codebase, I'm glad to have others like you by my side :)
