### ISSUE TITLE
Command execute with windows

### ISSUE THREAD

**Issue by haifenghuang** [abs-lang/abs#171]
In file `evaluator.go`, the `evalCommandExpression` funtion only execute with `bash`, I think that could be changed to support windows command as well, like below:

```go
        var commands []string
        var executor string
        if (runtime.GOOS == "windows") {
    	     commands = []string{"/C", cmd}
             executor = "cmd.exe"
        } else { //assume it's linux, darwin, freebsd, openbsd, solaris, etc
             commands = []string{"-c", cmd}
             executor = "bash"
        }

	c := exec.Command(executor, commands...)
	c.Env = os.Environ()
	var out bytes.Buffer
	var stderr bytes.Buffer
	c.Stdin = os.Stdin
	c.Stdout = &out
	c.Stderr = &stderr
	err := c.Run()
```

**Comment by odino** [comment]
Hi @haifenghuang, thanks for reporting this! Just a querstion from my side, wouldn't bash be available with the [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)?

**Comment by haifenghuang** [comment]
I know, but not all Windows systems have WSL. Further more,sometimes people really want to use the windows command.

**Comment by ntwrick** [comment]
ABS works in WSL. This is just Ubuntu in a container on x86_64 machine architecture. So WSL is just standard Linux with a mount to the Cdrive and a bash shell.

If we want to run an abs.exe native in win10 we can, but as OP points out we would have to invoke either cmd.exe or power shell to run any other windows executable.

**Comment by odino** [comment]
Not against using `cmd.exe` by default on windows. I don't actually have a windows machine to test -- @ntwrick any chance you could help with this whenever you get some time?

**Comment by odino** [comment]
BTW @haifenghuang well done with magpie -- we're [borrowing](https://github.com/abs-lang/abs/issues/177) :)
