### ISSUE TITLE
Option Parser

### ISSUE THREAD

**Issue by dangerousHobo** [abs-lang/abs#187]
What are the plans for handling/parsing options? Like getopt or zparseopts, it would be nice if abs supported an easy way to define options and parse/map them to variables.

**Comment by odino** [comment]
You can `x = flag('my-flag')` and then call a script with `abs script.abs --my-flag xyz`. Would that work for you? :)

**Comment by odino** [comment]
Ref: https://www.abs-lang.org/types/builtin-function

**Comment by dangerousHobo** [comment]
Yes! Perfect

**Comment by odino** [comment]
:+1+
