### ISSUE TITLE
Feature request: syntax highlighting plugin for *insert favorite text editor here*

### ISSUE THREAD

**Issue by ashelleyPurdue** [abs-lang/abs#208]
Might be too early to start thinking about this, but it'd be nice to have syntax highlighting.  No rush or anything, just figured I'd throw this out there so it gets on the to-do list.

**Comment by odino** [comment]
Not waaaay to early as we've been thinking about this -- the problem being that we'd have to pick an editor first. We might start with something such as vscode at some point, but I think it'll take some time unless someone from the community wants to get the ball rolling :)

**Comment by htejera** [comment]
Hi, 

A simple (and arbitrary) ABS [user-defined language](http://docs.notepad-plus-plus.org/index.php/User_Defined_Languages) syntax highlighting for **Notepad++**  to be used with default style.

https://github.com/htejera/abs-lang-npp

**Comment by odino** [comment]
Thanks a bunch! :)

**Comment by odino** [comment]
BTW yesterday I got around a basic VS code extension to provide very minimal support :) I'll publish it tonight. Once it's published, we'll include both the VS code one and @htejera's one in the documentation.

**Comment by odino** [comment]
https://github.com/abs-lang/vscode-abs
