### ISSUE TITLE
Deprecation of $() in favor of `

### ISSUE THREAD

**Issue by odino** [abs-lang/abs#220]
@ntwrick I think the `` `cmd` `` syntax has proven to be way easier than `$(cmd)`. What do you say we start deprecating the latter? No need to remove features, but I'd, for example, like to clean up the docs.

**Comment by ntwrick** [comment]
Agree

**Comment by tehmul** [comment]
Eek. My eyesight finds $(...) easier to read. Backquotes are hard to discern for me.

**Comment by odino** [comment]
I think it really depends how long you've been at it -- backticks are less characters, so for me that's what it really boils down to. I'm putting it out there -- if many of our users would like to stick to the `$()` syntax we would definitely reconsider it.

**Comment by kmptkp** [comment]
Please keep `$(cmd)` for the comfort of embedding, eg `dname = $(basename $(dirname "/tmp/make/life/easy"))`

**Comment by odino** [comment]
I want ABS to be very pragmatic, so the less typing the better.

At the same time, rather than removing `$()` (since a few seem to be happy with it) I'd suggest we simply "recommend" backticks for regular commands, and `$()` when embedding, so there's no need to do weird escapes.

How about that?

**Comment by kmptkp** [comment]
Recommending backticks as the default style sounds good! (I agree with 'pragmatic', but also think that pragmatic includes "don't make things unnecessarily complicated", such as embedding commands ;) Embedding commands with just backticks becomes very unpleasant.)
