### ISSUE TITLE
> and >> should support strings and act as file writers

### ISSUE THREAD

**Issue by odino** [abs-lang/abs#223]

**Comment by odino** [comment]
@ntwrick what do you think?

**Comment by ntwrick** [comment]
How would you use this? Does this also support generic IO redirection like
2>&1 or &> ?

**Comment by odino** [comment]
It's now a bit painful to dump multiline into a file from abs:

```
`echo $multiline_string > file.txt`
```

doesn't work as the input is truncated. So my main use case for this is to be able to do:

```
multiline_string > "file.txt"
```

...and that's about it -- no IO redirection or fancy stuff :)

**Comment by ntwrick** [comment]
Cool. And multiline_string < "file.txt" to read the file?

**Comment by odino** [comment]
I opted to remove the `<` as it can be achieved with `` multiline_string = `cat file.txt` ``
