### ISSUE TITLE
Try abs-lang directly from the browser

### ISSUE THREAD

**Issue by mingwho** [abs-lang/abs#236]
This will be super fun! If someone comes to abs-lang website or a new website and just try it out on the browser, like a mini version of Go playground.

**Comment by odino** [comment]
That would be great but it requires a sandboxed server to run ABS code -- so it's a bit complicated (esp. since we don't really run anything server-side on abs-lang.org). We'll keep this in mind but it's something that will take its time :)

**Comment by odino** [comment]
BTW yesterday night I actually merged https://github.com/abs-lang/abs/pull/260 so we now have a [playground on the website](https://www.abs-lang.org/playground) :)
