### ISSUE TITLE
hang on `$0` and on $($0)

### ISSUE THREAD

**Issue by kmptkp** [abs-lang/abs#248]
Running a script which contains either \`$0\` or $($0) hangs abs - same with any other $n passed to bash. (Sending an 'echo $1' to bash is the first thing I tried in abs, so I thought abs simply didn't work...). Note that the hang is slightly different in each case in that `$0` doesn't hang immediately (a echo(xyz) right after it will still print) whereas $($0) hangs immediately. Tested on osx and ubuntu, abs 1.5.0

**Comment by odino** [comment]
Thanks a bunch for reporting this, will have a look!

**Comment by kmptkp** [comment]
Playing with it more, there are two separate issues: first, instead of hanging it would be nice to report an error, ideally an informative error of the type "there is no abs variable $0, if you meant to reach a shell variable, please escape it with \$0". Second, once the bash variable is escaped, the result of running `$(echo \$0)` is ... `$0` which is a little confusing!
