### ISSUE TITLE
parsing bug: $() inside if

### ISSUE THREAD

**Issue by kmptkp** [abs-lang/abs#252]
Starting from a simple:

`mtype = $(uname -m)`
`if mtype == "x86_64" {}`

the exact equivalent substituting the mtype expression inside the `if` triggers a parsing error:

`if $(uname -m) == "x86_64" {}`

ie `expected next token to be $(), got IDENT instead`. (Adding parentheses doesn't help.) The backtick version works:

`if `\`uname -m\` `== "x86_64" {}`

**Comment by odino** [comment]
Unfortunately that's one of the limitations we have on commands, you'll
need them to be in their own line (check the docs):

https://www.abs-lang.org/syntax/system-commands

The backtick syntax makes is a lot easier and that is why I'm lobbying for
it :) I would be more inclined to have an external contribution that fixes
it as we're going to be focused on other things while commands work pretty
well for now, esp. when using the backtick syntax.

**Comment by kmptkp** [comment]
Aha, sorry, I missed that! Still getting used to abs. It makes total sense to standardize on backticks, keeping `$()` for the special cases where they work better.
