### ISSUE TITLE
JSON export into file

### ISSUE THREAD

**Issue by peteraba** [abs-lang/abs#295]
Running the following script, I see a properly formatted JSON on my console, but end up with something else in `s.json`

```abs
#! /usr/local/bin/abs

s = '{"a": 1, "b": "string", "c": true, "d": {"x": 10, "y": 20}}'
echo(s)
`echo "$s" > s.json`
```

console output:
```
{"a": 1, "b": "string", "c": true, "d": {"x": 10, "y": 21}}
```

`cat s.json` output:
```
{a: 1, b: string, c: true, d: {x: 10, y: 21}}
```

First and foremost, I believe the output should be the same, but at least the difference should be explained. If the non-JSON file makes sense for some of the supported use cases, I think it should be clear how to "export" the JSON formatted string.

**Comment by peteraba** [comment]
I did figure this out, but I'll probably also create a PR to improve the docs a bit.

Solution:
```abs
#! /usr/local/bin/abs

s = '{"a": 1, "b": "string", "c": true, "d": {"x": 10, "y": 20}}'
j = s.json()
j.d.y = 21
j.str() > "j.json"
`cat h.json`
# {"a": 1, "b": "string", "c": true, "d": {"x": 10, "y": 21}}
```

**Comment by odino** [comment]
@peteraba glad you found the solution :) sorry for lagging!

**Comment by peteraba** [comment]
@odino thanks for the comment.

Actually I was thinking that while I did find a workaround, this still may be an issue.

This code for example will work:
```abs
⧐  my_var = {"a": 23}
⧐  my_var.str() > 'tmp.json'
true
⧐  a = `cat tmp.json | jq .a`
⧐  a
23
```

But it won't work without the temporary file, or if it is solvable, I'm not sure how:
```abs
⧐  my_var = {"a": 23}
⧐  my_str = my_var.str()
⧐  a = `echo $my_str | jq .a`
⧐  a
parse error: Invalid numeric literal at line 1, column 3
```

**Comment by homebrew79** [comment]
@peteraba 

I ran into this issue a couple days ago. The best way to troubleshoot this is to echo out your command.
`
echo('echo $my_str | jq .a')
`

Then paste that output into bash, and you'll see the parse error is coming from jq. The fix is to quote the variable:
``
a = `echo '$my_str' | jq .a`
``

**Comment by odino** [comment]
@peteraba exactly what @homebrew79 said. ABS doesn't make an effort to quote/unquote things for bash, so you need to make sure your bash command is correctly quoted. What you're trying to do is basically:

```
echo {"a": 23} | jq .a
```

which would fail even in your regular terminal. It can be solved with the single quotes:

```
echo '{"a": 23}' | jq .a
```

Cheers!

**Comment by peteraba** [comment]
Makes sense, not sure why I missed this. Thank you both!

**Comment by odino** [comment]
No probs! Have fun with and and report back if there's any issue :)
