### ISSUE TITLE
split and join should not require an argument

### ISSUE THREAD

**Issue by odino** [abs-lang/abs#307]
...and use `""` as default.

**Comment by sysread** [comment]
I just sent a PR for updating `join` along with updates to `validateVarArgs` to support that.

**Comment by sysread** [comment]
I got bored and updated `split`, defaulting to a single space (e.g. `"foo bar".split()` -> `["foo", "bar"]`). It would be plenty easy to change that, obviously.

**Comment by odino** [comment]
:slightly_smiling_face:  thanks!
