### ISSUE TITLE
Call a defined function from command line return unknown file attribute: H

### ISSUE THREAD

**Issue by gcaggia** [abs-lang/abs#322]
I am trying to do the following, in a file named **script.abs**:
```
#! /usr/local/bin/abs

abs_test() {
  echo("Hello world!")
}
```
Then I source this file with `source script.abs`.

Then from the command line, I try to do the following to call my defined function. As I do with a bash script:
```
$ abs_test
```
I got the following error: `abs_test:1: unknown file attribute: H`

It is normal, did I make any mistake?

Thank you

**Comment by odino** [comment]
Hey @gcaggia, thanks for dropping by :)

You're trying to include ABS code in bash, which is not possible -- think of it of you sourcing a python file and trying to execute a python function in bash.

You will need to execute your abs code with `abs $file.abs`.
