### ISSUE TITLE
push function break loop

### ISSUE THREAD

**Issue by dinh** [abs-lang/abs#324]
This code shows [0] instead of [0,1,2,3,4,5,6,7,8,9]
```
names = []
for x = 0; x < 10; x = x + 1 {
    names.push(x)
}
echo(names)
```

**Comment by odino** [comment]
This is a bug due to https://github.com/abs-lang/abs/pull/316 as the line inside the loop gets interpreted as an automated return statement.

You can fix this for now by using:

```
names = []
for x = 0; x < 10; x = x + 1 {
    names = names.push(x)
}
echo(names)
```

Thanks for opening the issue -- will have a look at it soon-ish!

**Comment by odino** [comment]
@dinh you should be able to download `1.11.1` which should fix your issue for good :)

**Comment by odino** [comment]
https://github.com/abs-lang/abs/releases/tag/1.11.1
