### ISSUE TITLE
add hash std functions

### ISSUE THREAD

**Issue by odino** [abs-lang/abs#36]

**Comment by ntwrick** [comment]
Working on this now. 

Already have the basic hash.keys(), .values(), and .items() functions. What is your priority list for hash functions that are the most useful?

**Comment by odino** [comment]
I think that's about it? :)

Something I'm a bit worried about is that if the hash is initialised like
this:

a = {items: []}

when you access a.items you should receive the list inside the hash, not
the items function. Can you double check that it works that way?

**Comment by ntwrick** [comment]
NTW, this scenario is working correctly.
```bash
⧐  h = {"items": [1,2,3]}
⧐  h
{items: [1, 2, 3]}
⧐  h.items()
[[items, [1, 2, 3]]]
⧐  h += {"x": 1, "y": 2}
⧐  h
{items: [1, 2, 3], x: 1, y: 2}
⧐  h.items()
[[items, [1, 2, 3]], [x, 1], [y, 2]]
⧐  h.items
[1, 2, 3]
```

**Comment by odino** [comment]
Great!

**Comment by odino** [comment]
@ntwrick once you accept the invitation into the org this issue can be "officially" assigned to you! :heart:
