### ISSUE TITLE
Platform Support

### ISSUE THREAD

**Issue by bammi** [abs-lang/abs#380]
I just discovered abs-lang  and am enthusiastic about the tenants. I looked through all the docs and cannot figure platforms that are supported, in particular Windows or plans for Windows. The only reference i can find to platform agnostic approach is the justification for using go lang. 
Support for Windows is important because there is crying need for a competent scripting language in windows (cmd and MS Power Shell are both embarrassments). I currently use Cygwin Bash to write portable scripts across platforms that i have to support, and i am quite comfortable with .sh but clearly see the need for abs

I am willing to give abs a serious try only if it truly multi platform and not unix-like only.

**Comment by odino** [comment]
Windows should be supported -- you can test one of the releases [here](https://github.com/abs-lang/abs/releases).

https://github.com/abs-lang/abs/releases/download/2.2.1/abs-windows-386.exe
https://github.com/abs-lang/abs/releases/download/2.2.1/abs-windows-amd64.exe

Caveat: one of ABS' most powerful features (system commands) works [a bit differently on windows](https://www.abs-lang.org/syntax/system-commands.html) (we use cmd.exe vs bash -- but you could use bash by running ABS through the WSL).

Let me know if this doesn't answer your question!
