### ISSUE TITLE
ceil/floor bug with negative floats

### ISSUE THREAD

**Issue by gromgit** [abs-lang/abs#382]
```
> -10.6.ceil()
-11   # should be -10
> -10.6.floor()
-10   # should be -11
> -10.6.round()
-11
> -10.6.int()
-10
```

**Comment by odino** [comment]
I think this is very similar to the other issue. We first ceil / floor the
float, then make it negative:)

Thanks for finding these, I'll try to give it a crack in the upcoming days

**Comment by gromgit** [comment]
:+1:, parenthesizing the negative number object gives correct results for all the math operations in both my PRs, so it just a parser issue.
