### ISSUE TITLE
between/clamp bug with negative numbers

### ISSUE THREAD

**Issue by gromgit** [abs-lang/abs#383]
```
> -10.between(-50, -1)
ERROR: unknown operator: -BOOLEAN
	[1:1]	-10.between(-50, -1)
> -10.clamp(-50, -1)
1  # should be -10
```
Parser issue?

**Comment by odino** [comment]
Yes, the prefix operator needs it's priority to be bumped. Thanks for
finding this out!

I assume (-10).between(...) will work as a temporary workaround

**Comment by gromgit** [comment]
:+1:, parenthesizing the negative number object gives correct results for all the math operations in both my PRs.
