### ISSUE TITLE
echo() Error: percent character '%' missing 

### ISSUE THREAD

**Issue by Bad3r** [abs-lang/abs#424]
Hi,
I ran into a weird problem. Here is the example code
```ps
#! /usr/local/bin/abs

testSTR0    = "~@#$%^&*()_+-=\/.,?><" 
testSTR1    = "this%is%a%test"
testSTR2    = "this@is@a@test"

echo("testSTR0: "    + testSTR0)
echo("testSTR1: "    + testSTR1)
echo("testSTR2: "    + testSTR2)
```
As you can see the file contains 3 test strings with special characters.
when running this script the output is
```py
testSTR0: ~@#$%!^(MISSING)&*()_+-=\/.,?><
testSTR1: this%!i(MISSING)s%!a(MISSING)%!t(MISSING)est
testSTR2: this@is@a@test
```
The expected output is
```py
testSTR0: ~@#$%!^%&*()_+-=\/.,?><
testSTR1: this%is%a%test
testSTR2: this@is@a@test
```
This doesn't seem  to only effect the `echo()` function. I think this issue effects all strings containing `%`.

**Comment by odino** [comment]
This is because the % sign then expects a variable to be specified, in order to replace the original string. What you want to do is to escape the % with %%:

```
⧐  echo("this%is%a%test")
this%!i(MISSING)s%!a(MISSING)%!t(MISSING)est

⧐  echo("this%%is%%a%%test")
this%is%a%test
```

Works? :smile:

**Comment by odino** [comment]
I should update the doc though... :)

**Comment by odino** [comment]
Updated docs:

https://www.abs-lang.org/types/string/#fmt
https://www.abs-lang.org/types/builtin-function/#echo-var
