### ISSUE TITLE
joining an array into a multi line string

### ISSUE THREAD

**Issue by Bad3r** [abs-lang/abs#425]
I am trying to join an array of strings into a string separated by a new line `\n`
here is an example code that should illustrate the issue.
note that some of the lines are commented out and the output is in the same line
```py
#! /usr/local/bin/abs

testSTR0    = "test1" 
testSTR1    = "test2"
testSTR2    = "test3"

arr0        = [testSTR0, testSTR1, testSTR2]
# echo(arr0)            #= ["test1", "test2", "test3"]

arr1        = arr0.join('\n')
# echo(arr1)            #= test1 \n test2 \n test3

arr2        = [testSTR0 + '\n', testSTR1 + '\n', testSTR2 + '\n']
# echo(arr2)            #= ["test1\n", "test2\n", "test3\n"]

arr3        = arr2.join()
# echo(arr3)            #= test1\ntest2\ntest3\n
# `echo $arr3 > t.txt`   #= test1ntest2ntest3n
```

The expected output to `t.txt`
```
test1
test2
test3
```

is there a different way to get this result?

**Comment by Bad3r** [comment]
My bad. the issue is that i used a single quote `'`character around `\n` (i.e `'\n')
The correct way is to use double quotes `"`  --> `"\n"`
fixed example code:
 ```py
#! /usr/local/bin/abs

testSTR0    = "test1" 
testSTR1    = "test2"
testSTR2    = "test3"

arr0        = [testSTR0, testSTR1, testSTR2]
# echo(arr0)            #= ["test1", "test2", "test3"]

arr1        = arr0.join("\n")
# echo(arr1)
# test1
# test2
# test3
```
more details in the documentation page  [types/string/#working-with-special-characters-in-string-functions](https://www.abs-lang.org/types/string/#working-with-special-characters-in-string-functions)
closed

**Comment by odino** [comment]
Thanks 😊 for digging in yourself!
