### ISSUE TITLE
Installation script fails on Apple Silicon

### ISSUE THREAD

**Issue by jamesgecko** [abs-lang/abs#460]
The output of `uname -m` on newer Apple M1 laptops is `arm64`. But the `install.sh` script builds the following URL, which does not exist:
```
https://github.com/abs-lang/abs/releases/latest/download/abs-darwin-386
```

Intel builds will work on M1 if Rosetta 2 is installed, so a quick fix would be to download the `abs-darwin-amd64` binary instead. A long term solution is probably building a `abs-darwin-arm64` binary.

**Comment by odino** [comment]
@jamesgecko could you try the following installer and let me know if it works?

https://gist.github.com/odino/4795c7707964a25af2cb566493edd7ae

**Comment by odino** [comment]
this should be fixed -- feel free to re-open if needed

https://github.com/abs-lang/abs/blob/master/docs/src/.vuepress/dist/installer.sh
