### ISSUE TITLE
Allow `json` to be called on all JSON types

### ISSUE THREAD

**Issue by odino** [abs-lang/abs#54]
currently, `"[1, 2, 3]".json()` does not work

**Comment by kseistrup** [comment]
Related: abs doesn't seem to recognize `null`:

```
⧐  "{\"x\": null}".json()
ERROR: identifier not found: null
```

I will be happy to open a separate issue if it doesn't belong here.

**Comment by odino** [comment]
Oh, great catch. Would you mind opening another issue? I can take a look at
this quickly, as it's fairly important -- while the original issue with
JSON types can take some time.

**Comment by kseistrup** [comment]
For `null`, please see #85.
