### ISSUE TITLE
Parallel commands

### ISSUE THREAD

**Issue by odino** [abs-lang/abs#70]
## Syntax

```
`command &`
```

Just like you would do on a bash terminal. This has the disadvantage of not being 100% 1:1 with windows, but we'll get there eventually (I think on win you simply use `start command` so it shouldn't be a big thing).

The command will run without blocking execution.

## Waiting

```
cmd.wait()
```

## Testing whether a command has been executed

```
cmd.done
```

**Comment by odino** [comment]
Example:

```
ip = $(curl canihazip.com)
echo("sending request...")
ip.wait()
echo(ip)
```

**Comment by odino** [comment]
Here some possible scenarios:

```
$$(sleep 10)
&(sleep 10)
&$(sleep 10)
$(sleep 10)&
$`sleep 10`
&`sleep 10`
`sleep 10`&
bg`sleep 10`
bg$(sleep 10)
```

They all seem very wonky, so not sure right now.

In order to wait / do something after execution here's what I'm thinking:

```
cmd = ...

cmd.wait()
..do things...

# and
cmd.on('end', f(res) { ..do things...})

# and
if cmd.done() {
  ..do things...
}
```

I think supporting all 3 of them is not a big problem, my main worry is the syntax do declare background commands. Bash does this beautifully with the trailing `&`, so I'm leaning towards `` `sleep 10` & ``

Thought of the day: `` `sleep 10&` `` blocks in ABS. If we can find a way to understand whether the process is running in background then we're sorted and don't need any special syntax. [Ref](https://stackoverflow.com/a/48558674/934439). We could even "fake" this whole process by checking whether the last char of our command is an `&`, and turn that into a background command automagically. Very on the fence at the moment :)

**Comment by odino** [comment]
Syntax and issue updated, I will start on this now.

**Comment by shahidhk** [comment]
Is there a way to kill a background command?

**Comment by odino** [comment]
We'll push something in [1.3](https://github.com/abs-lang/abs/issues/198)
