### ISSUE TITLE
Please suppress return values when equal to `null`

### ISSUE THREAD

**Issue by kseistrup** [abs-lang/abs#92]
Perhaps as a side effect of fa0c4594aa78887d1bf5140788890087170ecdd3 the REPL is now showing `null` after e.g. simple assignments:

```sh
⧐  x=3
null
```

This is a bit distracting (even if it may be the true return value). Perhaps return values should only be shown if they are not `null`?

**Comment by odino** [comment]
I think it's fair, but I would wait to get some feedback from outside as well. Ruby's REPL, for example, follows the same:

```
irb(main):001:0> a = nil
=> nil
irb(main):002:0> a
=> nil
```

I think Node might do the same as well. I'm worried that if one sets something explicitly to null it'd be weird not to see it in the repl:

```
⧐  x=null
⧐  x
(nothing happens)
```

wdyt?

**Comment by kseistrup** [comment]
I agree about the last thing (nothing happens), that would be weird. But I also think we're in a different context than an assignment: Saying `x` is an implicit ‘show me the value of x’, whereas `x=null` is asking for an assignment, not the return value.

I'm fine with whatever you choose (although I still prefer not seeing nulls for every move I make), and you needn't choose now – I just wanted to report a change in behaviour, and I liked the previous behaviour more.

**Comment by kseistrup** [comment]
PS: I was thinking: What if the return value is stored in an ‘internal’, read-only, variable (like Bash's `$?`) instead?

**Comment by odino** [comment]
@kseistrup been thinking about [something similar](https://github.com/abs-lang/abs/issues/34), but mostly for `$()` commands -- that would make it more familiar for people coming from bash.

I don't think it would also be nice to have something like this in the REPL:

```
⧐  1 + 2
(nothing happens)
```

but I'm somewhat inclined to suppress all nulls in the REPL for now. I see what python does and I generally tend to lean that direction as it's probably the most pragmatic language I bumped across. I will give myself a few days just to think this through -- hopefully other can jump in. In other news, I also want to fix the REPL output, as strings are not printed with quotes (string vs "string"). When that is done, skipping nulls in the REPL will be a breeze.

BTW, I see you've been playing quite a bit with ABS -- how does it feel so far? Transparent feedback is always welcome, so don't hold back :)

**Comment by kseistrup** [comment]
I totally agree with the `1+2` thing, that would be a very confusing and counter-intuitive experience.

I have yet to recompile the latest git version, but thanks for your responsiveness.

> how does it feel so far?

Overall I have a good feel and sense a potential, which is why I keep playing with the REPL.

I haven't used ABS for ‘a real script’ for ‘a real situation/task’ yet (but I probably should). I have mostly been moving around to see where the limits of the box are – and as you have seen, I found a few.

Ever since I left Amiga and its REXX implementation ARexx back in 1995 and switched to Linux, Python has been my favourite language. I still do a little C, and Bash scripts are also common, but the majority of what I do is in Python. So it wasn't at all difficult to get started with ABS.

I think what I miss the most when comparing with Python is introspection:

```sh
⧐  res = $(date)
null  # I'm still on an earlier incarnation
⧐  res.ok
true  # Expected
⧐  type(res)
STRING
⧐  s = "abc"
null
⧐  s.ok
false  # I'm unsure how to interpret this
⧐  s.foo  # Can I choose anything, like with hashes?
ERROR: invalid property 'foo' on type STRING  # If `.foo` isn't there, what is (apart from `.ok`)?
```

But perhaps that's just because I'm still learning what ABS has to offer. If I knew exactly what is there, I probably wouldn't need introspection (I can write in Bash and C without having introspection, so I'm probably just spoiled by Python).

The documentation doesn't answer all questions I have, but I also know that ABS is at an early stage and I know how much it sucks to write documentation – and it sucks even more for ABS because it is still a moving target, but I'm happy to play along. (Aside: There are a few downright errors in the examples in the documentation, is it possible to submit PRs for the docs?)

I always have a Python REPL running somewhere, for easy calculations etc. Sometimes these REPLs are Xonsh or TakoShell (both hybrid python + shell REPLs). Perhaps ABS could be such a REPL when it reaches a more mature state. I'm still unsure about the answer to the question: What does ABS offer that really sets it apart from Python/Xonsh/Tako/Bash, that would make me want to use it every day?

**Comment by odino** [comment]
> > how does it feel so far?
> 
> Overall I have a good feel and sense a potential, which is why I keep playing with the REPL.
> 

Thanks!

> I haven't used ABS for ‘a real script’ for ‘a real situation/task’ yet (but I probably should). I have mostly been moving around to see where the limits of the box are – and as you have seen, I found a few.
> 
> Ever since I left Amiga and its REXX implementation ARexx back in 1995 and switched to Linux, Python has been my favourite language. I still do a little C, and Bash scripts are also common, but the majority of what I do is in Python. So it wasn't at all difficult to get started with ABS.

Happy to hear that!

> 
> I think what I miss the most when comparing with Python is introspection:
> 
> ```shell
> ⧐  res = $(date)
> null  # I'm still on an earlier incarnation
> ⧐  res.ok
> true  # Expected
> ⧐  type(res)
> STRING
> ⧐  s = "abc"
> null
> ⧐  s.ok
> false  # I'm unsure how to interpret this
> ⧐  s.foo  # Can I choose anything, like with hashes?
> ERROR: invalid property 'foo' on type STRING  # If `.foo` isn't there, what is (apart from `.ok`)?
> ```
> 
> But perhaps that's just because I'm still learning what ABS has to offer. If I knew exactly what is there, I probably wouldn't need introspection (I can write in Bash and C without having introspection, so I'm probably just spoiled by Python).
> 
> The documentation doesn't answer all questions I have, but I also know that ABS is at an early stage and I know how much it sucks to write documentation – and it sucks even more for ABS because it is still a moving target, but I'm happy to play along. (Aside: There are a few downright errors in the examples in the documentation, is it possible to submit PRs for the docs?)

I'm trying to keep the doc as updated as possible, but if you find any mistake feel super-free to send a PR!

> 
> I always have a Python REPL running somewhere, for easy calculations etc. Sometimes these REPLs are Xonsh or TakoShell (both hybrid python + shell REPLs). Perhaps ABS could be such a REPL when it reaches a more mature state. I'm still unsure about the answer to the question: What does ABS offer that really sets it apart from Python/Xonsh/Tako/Bash, that would make me want to use it every day?

I wouldn't use ABS primarily as a REPL -- [this](https://www.abs-lang.org/introduction/why-another-scripting-language) should clarify some things.

Long story short, I believe bash is amazing because of its seamless integration with the underlying system; at the same time, the syntax is fairly wonky. ABS tries to keep a very clean integration with the system with a more "modern" syntax, a syntax I'm trying to keep as terse as possible as that's one of the [big wins with shell languages](https://news.ycombinator.com/item?id=10068058).

**Comment by kseistrup** [comment]
> ABS tries to keep a very clean integration with the system with a more "modern" syntax

I agree with the more modern syntax. If Python hadn't used blanks and indentation level as blok markers, it could have evolved into something like ABS. I like ABS' syntax.

However, I feel that ABS is further away from the underlying system than Bash is. I feel it's more on the level with Python. The reason is that I have to wrap system commands in `$()` rather than just running them directly, as in a traditional shell.

In comparison, [Tako](https://takoshell.org/ "Tako Shell is a command language and shell for GNU/Linux (and Mac OS, and Windows via Cygwin or MSYS2), based on Python (version 3) and GNU Bash, and forked from xonsh.") feels like a seemless mixture of shell and python: I can run commands directly, like at a Bash promtp, and I can also use python constructs. Its development seems to have stalled, though, so I'm reluctant to use it for anything serious. And its older sibling, [Xonsh](http://xonsh.org/ "Xonsh is a Python-ish, BASHwards-looking shell language and command prompt.") has become too heavy and slow to my taste.

The current [Oil Shell](https://www.oilshell.org/ "Oil is a new Unix shell.") fails to run here, but I'm keeping an eye on the project.

----

Other contenders:

* [elvish](https://elv.sh/ "Elvish is a friendly interactive shell and an expressive programming language.")
* [oh](https://github.com/michaelmacinnis/oh "A surprisingly powerful Unix shell")

**Comment by odino** [comment]
I'll be very honest, the intention wasn't to build a repl / shell but
rather a scripting alternative to bash that would be more terse than others
(python for example). So using it as a shell might be a bit painful :)

**Comment by kseistrup** [comment]
> […], the intention wasn't to build a repl / shell but rather a scripting alternative to bash that would be more terse than others

At its current state, ABS is most suitable as a REPL for me: The way it implements system commands makes it less suitable as a scripting language because I have to wrap everything in `$()` and – equally important – because it lacks several builtin functions that cannot be run in subshells. E.g., it doesn't make sense to `res = $(cd /path/to/somewhere)` or `res = $(umask 0027)` because the effect is not seen in the parent shell (ABS).

I am aware that ABS is at a very early stage, so I'm not too pessimistic about the future. :wink:

Happy new year! :sparkle:
